core/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from main import views

#enable for API to frontend
#router= routers.DefaultRouter()
#router.register(r'task', views.Viewtasks)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls"))
    
]

main/urls.py
from django.urls import path
from .views import RegistrationView, ApiLoginView, ApiLogoutView, TaskListCreateView, TaskRetrieveUpdateDeleteView
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, RegisterPage, TaskReorder
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('', TaskList.as_view(), name="tasks"),
    path('register/', RegisterPage.as_view(), name="register" ),
    path('login/', CustomLoginView.as_view(), name='custom-login'),    
    path("logout/", LogoutView.as_view(next_page= 'custom-login'), name='logout'),
    path("task/<int:pk>/", TaskDetail.as_view(), name="task"),
    path("create-task/", TaskCreate.as_view(), name="task-create"),
    path("update/<int:pk>/", TaskUpdate.as_view(), name= "task-update"),
    path('delete/<int:pk>/', TaskDelete.as_view(), name="task-delete"),
    path('task-redorder', TaskReorder.as_view(), name='task-reorder'),
    #API URLS HERE:
    path('api/register/', RegistrationView.as_view(), name='api-register'),
    path('api/login/', ApiLoginView.as_view(), name='api-login'),
    path('api/logout/', ApiLogoutView.as_view(), name='api-logout'),
    path('api/create/', TaskListCreateView.as_view(), name="api-create"),
    path('api/tasks/<int:pk>/', TaskRetrieveUpdateDeleteView.as_view(), name='api-task-detail'),
]

main/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class Profile(models.Model):
    account = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank= True)
    tasks = models.ForeignKey("Task", on_delete=models.CASCADE, related_name="user_tasks", null=True, blank=True)

    def __str__(self):
        return self.account.username
    


class Task(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="created_tasks")
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    reminder = models.DateTimeField(null=True, blank=True)
    start_time = models.DateTimeField(auto_now_add=True)
    finish_time = models.DateTimeField(null=True, blank=True)

    def mark_as_complete(self):
        self.complete = True
        self.finish_time = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-complete"]

@receiver(post_save, sender=Task)
def task_created(sender, instance, created, **kwargs):
    if created:
        instance.start_time = timezone.now()
        instance.save()
        # Send an email when a new task is created
        subject = 'New Task Created'
        message = f'A new task "{instance.title}" has been created at {instance.start_time}'
        recipient_list = [instance.created_by.email]
        send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list)

@receiver(post_save, sender=Task)        
def task_completed(sender, instance, **kwargs):
    if instance.complete and not instance.finish_time:
        # Task has been completed
        instance.finish_time = timezone.now()
        instance.save()

        # Send an email when a task is completed
        subject = 'Task Completed'
        message = f'The task "{instance.title}" has been completed at {instance.finish_time}'
        recipient_list = [instance.created_by.email]
        send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list)

@receiver(pre_delete, sender=Task)
def task_deleted(sender, instance, **kwargs):
    subject = 'Task Deleted'
    message = f'The task "{instance.title}" has been deleted.'
    recipient_list = [instance.created_by.email]
    send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list)

@receiver(post_save, sender=Task)
def send_reminder_email(sender, instance, **kwargs):
    if instance.reminder and instance.reminder == timezone.now():
        subject = 'Task Reminder'
        message = f'Reminder for the task "{instance.title}"'
        recipient_list = [instance.created_by.email]
        send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(account=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PositionForm(forms.Form):
    position= forms.CharField()

class UserCreationForm(UserCreationForm):
    email= forms.EmailField(required= True, label='Email')
    class Meta:
        model= User
        fields=("username", "email", "password1", "password2")
        
    def save(self, commit= True):
        user= super(UserCreationForm, self).save(commit= False)
        user.email= self.cleaned_data['email']
        if commit:
            user.save()
        return user

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .serializers import TaskSerializer, ProfileSerializer, UserSerializer
from rest_framework import generics, permissions
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import APIView
from django.contrib.auth import login, logout, authenticate
from django.utils.decorators import method_decorator
from rest_framework.authtoken.models import Token
from rest_framework import viewsets
from .models import Task, Profile
from rest_framework import status
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from .forms import PositionForm, UserCreationForm
from django.db import  transaction


class CustomLoginView(LoginView):  
    model=Task
    template_name: str= 'base/login.html'
    fields= ['username', 'password']
    redirect_authenticated_user= True

    def get_success_url(self):
        return reverse_lazy('tasks')

class RegisterPage(FormView):
    template_name= 'base/register.html'
    form_class= UserCreationForm
    redirect_authenticated_user=True
    success_url= reverse_lazy('tasks')

    def form_valid(self, form):
        user= form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage, self).get(*args, **kwargs)

class TaskList(LoginRequiredMixin, ListView):
    login_url = 'login/'
    template_name = 'base/task_list.html'
    model = Task
    context_object_name = "tasks"  # by default this is "object_list"

    def get_queryset(self):
        # Filter tasks based on the logged-in user
        return Task.objects.filter(created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains=search_input)
        context['search_input'] = search_input
        return context
class TaskDetail(LoginRequiredMixin, DetailView):
    #detailview looks for object
    model= Task
    context_object_name: str= 'task' #by default this is object
    template_name: str= "base/task.html" #by default list view finds a html template with named after the class it's assigned to. this function "template_name" is to change such

class TaskCreate(LoginRequiredMixin, CreateView): 
    model = Task
    template_name = 'base/task_form.html'
    fields = ['title', 'description', 'complete', 'reminder']
    success_url = reverse_lazy("tasks")

    def form_valid(self, form):
        form.instance.created_by = self.request.user  # Set the creator to the logged-in user
        return super().form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model= Task
    template_name= "base/task_form.html"
    fields= ['title', 'description', 'complete', 'reminder']
    success_url= reverse_lazy("tasks")

class TaskDelete(LoginRequiredMixin, DeleteView):
    model=Task
    template_name="base/task_confirm_delete.html"
    context_object_name: str= "task"
    success_url= reverse_lazy("tasks")
    def get_queryset(self):
        owner= self.request.user
        return self.model.objects.filter(created_by=owner)

class TaskReorder(View):
    def post(self, request):
        form = PositionForm(request.POST)
        if form.is_valid():
            position_list = form.cleaned_data["position"].split(',')
            with transaction.atomic():
                self.request.user.set_task_order(position_list)
        return redirect(reverse_lazy('tasks'))

    
#BELOW  ARE THE VIEWS FOR THE API
class Viewtasks(viewsets.ModelViewSet):
    serializer_class= TaskSerializer
    queryset= Task.objects.all()
    permission_classes=(permissions.IsAuthenticated,)
    
class ProfileView(viewsets.ModelViewSet):
    serializer_class= ProfileSerializer
    queryset= Profile.objects.all()
    permission_classes= (permissions.IsAuthenticated,)
    
class TaskListCreateView(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

class TaskRetrieveUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = (permissions.IsAuthenticated,)

    
class RegistrationView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (permissions.AllowAny,)

class ApiLoginView(APIView):
    permission_classes = (permissions.AllowAny,)

    @method_decorator(csrf_exempt)
    def post(self, request):
        username = request.data.get('username')
        password = request.data.get('password')
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            token, created = Token.objects.get_or_create(user=user)
            return Response({'token': token.key})
        else:
            return Response({'error': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)

class ApiLogoutView(APIView):
    def post(self, request):
        if request.user.is_authenticated:
            request.auth.delete()
            logout(request)
            return Response(status=status.HTTP_200_OK)
        else:
            return Response({'error': 'Not authenticated'}, status=status.HTTP_401_UNAUTHORIZED)
# Create your views here.

main/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password.label}}</label>
        {{form.password}}

        <input class="button" type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
</div>
{%endblock%}

main/templates/base/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description"
        content="This is to do list implemented using Django by Dennis Ivy who is a full stack web developer.">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>To Do Items</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">

    <style>
        body {
            background-color: #FAFAFA;
            font-family: 'Nunito', sans-serif;
            padding-top: 50px;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6
            {
            font-family: 'Raleway', sans-serif;
        }

        a,
        p {
            color: #4b5156
        }

        a {
            font-weight: 600;
        }

        .container {
            max-width: 550px;
            margin: auto;
            background-color: #fff;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        }

        input {
            outline: none;
            border: none;
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #EEA390 0%, #EB796F 43%, #EB796F 100%);
        }

        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background-color: #fff;
            border-top: 1px solid #dfe4ea;
            overflow: hidden;
        }

        .task-title {
            display: flex;
            padding: 20px;
        }

        .task-title a {
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }

        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(105, 192, 105);
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius: 50%;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
            padding: 20px 0px;
        }

        /*Handle Classes*/

        .handle {
            display: inline-block;
            padding: 20px 16px;
            cursor: grab;
            user-select: none;
        }

        .handle:after,
        .handle:before {
            display: block;
            content: "";
        }

        .handle:active,
        .handle:active:before,
        .handle:active:after {
            cursor: grabbing;
        }

        .dropArea {
            background-color: #f1f2f6;
            color: black;
            border: #ced6e0 1px solid;
        }

        .selectedTask {
            opacity: 0.6;
        }


        #add-link {
            color: #EB796F;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;
        }

        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }

        @media screen and (max-width:320px) {
            #search-add-wrapper {
                padding: 10px;
            }
        }

        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #757575;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px !important;
            display: block;
        }

        ::placeholder {
            font-weight: 300;
            opacity: 0.5;
        }

        .button {
            border: 1px solid #757575;
            background-color: #FFF;
            color: #EB796F;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .card-body {
            padding: 20px;
        }
    </style>
</head>

<body>

    <div class="container">
        {% block content %} {% endblock content %}
    </div>

</body>


</html>

main/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.email.label}}</label>
        {{form.email}}
        
        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'custom-login' %}">Login</a></p>
</div>
{%endblock%}

main/templates/base/task.html
<h1>Task: {{task.description}}</h1>

main/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Go Back</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this task? <b>"{{task}}"</b> </p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>



{% endblock content %}

main/templates/base/task_form.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        <label>{{form.title.label}}</label>
        {{form.title}}

        <label>{{form.description.label}}</label>
        {{form.description}}

        <label>{{form.complete.label}}</label>
        {{form.complete}}

        <label>{{form.reminder.label}}</label>
        <input type="datetime-local" id="id_reminder" name="reminder">

        <input class="button" type="submit" value="Submit">
    </form>
</div>


{% endblock content %}

main/templates/base/task_list.html
{% extends 'base/main.html' %} {% block content %}

<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h3>
    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a> {% else %}
    <a href="{% url 'custom-login' %}">Login</a> {% endif %}
</div>


<div id="search-add-wrapper">
    <form method="GET" style="display: flex;">
        <input type='text' name='search-area' placeholder="Search your task" value="{{search_input}}">
        <input class="button" type="submit" value='Search'>
    </form>
    {% if tasks|length > 0 %}
    <a id="add-link" href="{% url 'task-create' %}">&#x2b;</a>
    {% endif %}
</div>


<!-- Hidden form. Form submits new item positions -->
<form style="display: none;" id="reorderForm" method="post" action="{% url 'task-reorder' %}">
    {% csrf_token %}
    <input type="hidden" id="positionInput" name="position">
</form>


<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper" data-position="{{task.pk}}">
        <div class="task-title">
            {% if task.complete %}
            <div class="task-complete-icon"></div>
            <table>
                <tr>
                    <th>Finished</th>
                    <th>Title</th>
                    <th>Start time</th>
                    <th>End time</th>
                </tr>

                <tr>
                    <td>{{task.complete}}</td>
                    <td><i><s>{{task.title}}</s></i></td>
                    <td><i><s>{{task.start_time}}</s></i></td>
                    <td>{{task.finish_time}}</td>
                </tr>
            </table>
            {% else %}
            <div class="task-incomplete-icon"></div>
            <table>
                <tr>
                    <th>Finished</th>
                    <th>Title</th>
                    <th>Start time</th>
                    <th>Reminder</th>
                </tr>
                <tr>
                    <td> {{task.complete}}</a> </td>
                    <td>{{task.title}}</td>
                    <td>{{task.start_time}}</td>
                    <td>{{task.reminder}}</td>
                </tr>
            </table>
            {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'task-delete' task.id %}">&#215;</a>
            <a href="{% url 'task' task.id %}"> details </a>
            <a href="{% url 'task-update' task.id %}"> update </a>
            <span class="handle">&nbsp;&#10247;</span>
        </div>
    </div>

    {% empty %}
    <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
        <h3>No new tasks are created.</h3>
        <h3>Create a <a style="text-decoration: none; color: #e53935;" href="{% url 'task-create' %}">New task</a> ! </h3>
    </div>
    {% endfor %}
</div>

<script>
    var taskList = document.getElementById("tasklist");
    var reorderForm = document.getElementById("reorderForm");
    var positionInput = document.getElementById("positionInput");

    let sortable = Sortable.create(taskList, {
        handle: '.handle',
        ghostClass: 'dropArea',
        chosenClass: 'selectedTask',

    });

    function reordering() {
        const rows = document.getElementsByClassName("task-wrapper");
        let pos = [];
        for (let row of rows) {
            pos.push(row.dataset.position);
        }
        console.log(pos.join(","))
        positionInput.value = pos.join(',');

        // Get the CSRF token and include it in the POST request
        var csrfToken = document.getElementsByName("csrfmiddlewaretoken")[0].value;

        // Send the POST request with the CSRF token
        var xhr = new XMLHttpRequest();
        xhr.open("POST", reorderForm.action, true);
        xhr.setRequestHeader("X-CSRFToken", csrfToken);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200) {
                    // Handle success if needed
                } else {
                    // Handle error if needed
                }
            }
        };
        xhr.send("position=" + pos.join(','));

        // Prevent the default form submission
        event.preventDefault();
    }

    document.ondrop = reordering;
</script>


{% endblock content %}